# Generated by Django 3.2.2 on 2021-05-06 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Nombre del análisis')),
                ('periodo', models.CharField(max_length=100, verbose_name='Periodo')),
                ('fechaInicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fechaFin', models.DateField(verbose_name='Fecha de fin')),
                ('fechaPaso', models.DateField(verbose_name='Fecha de paso')),
                ('archivo', models.FileField(upload_to='', verbose_name='Archivo')),
                ('tipoAnalisis', models.CharField(max_length=100, verbose_name='Tipo de análisis')),
                ('comentario', models.CharField(max_length=255, null=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Análisis',
                'verbose_name_plural': 'Análisis',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=200, verbose_name='Lugar')),
                ('altitud', models.CharField(max_length=20, null=True, verbose_name='Altitud')),
                ('latitud', models.CharField(max_length=12, null=True, verbose_name='Latitud')),
                ('longitud', models.CharField(max_length=12, null=True, verbose_name='Longitud')),
                ('operando', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Datos de la ubicación',
            },
        ),
        migrations.CreateModel(
            name='Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Cultivo')),
                ('nombreCientifico', models.CharField(max_length=100, verbose_name='Nombre científico')),
                ('descripcion', models.TextField(max_length=5000, verbose_name='Descripcion')),
                ('imagenes', models.ImageField(upload_to='imgcultivos', verbose_name='Foto')),
                ('mesDeSiembra', models.CharField(choices=[('Noviembre', 'Noviembre'), ('Agosto', 'Agosto'), ('Abril', 'Abril'), ('Junio', 'Junio'), ('Septiembre', 'Septiembre'), ('Febrero', 'Febrero'), ('Enero', 'Enero'), ('Julio', 'Julio'), ('Diciembre', 'Diciembre'), ('Octubre', 'Octubre'), ('Marzo', 'Marzo'), ('Mayo', 'Mayo')], default='Enero', max_length=30, verbose_name='Mes de siembra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, verbose_name='Clave')),
                ('nombreEntidad', models.CharField(max_length=50, verbose_name='Entidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacidad', models.TextField(max_length=5000, verbose_name='Política de privacidad')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la aplicación')),
                ('nombreContro', models.CharField(max_length=20, verbose_name='Nombre corto')),
                ('telefono', models.CharField(max_length=100, verbose_name='Contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Información',
                'verbose_name_plural': 'Datos de la aplicación',
            },
        ),
        migrations.CreateModel(
            name='MonitorSequia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensidad', models.CharField(max_length=50, verbose_name='Intensidad de la sequía')),
                ('descripcion', models.TextField(max_length=5000, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Monitor de sequía',
                'verbose_name_plural': 'Datos de la sequía',
            },
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperaturaMinima', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Temperatura mínima')),
                ('temperaturaMaxima', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Temperatura máxima')),
                ('temperaturaLeida', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Temperatura leída')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Temperatuta',
                'verbose_name_plural': 'Temperaturas',
            },
        ),
        migrations.CreateModel(
            name='PlanDeContingencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del plan')),
                ('activo', models.CharField(choices=[('Iniciado', 'Iniciado'), ('En Evaluación', 'En Evaluación'), ('Finalizado', 'Finalizado'), ('Desconocido', 'Desconocido'), ('En proceso', 'En proceso')], default='Desconocido', max_length=13, verbose_name='Estado del plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.area', verbose_name='área')),
            ],
            options={
                'verbose_name': 'Plan de contingencia',
                'verbose_name_plural': 'Planes de contingencia',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, verbose_name='Clave')),
                ('nombreMunicipio', models.CharField(max_length=200, verbose_name='Municipio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entidad', verbose_name='Entidad')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='CensoTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura1', models.DecimalField(decimal_places=1, default=26.0, max_digits=5, max_length=6, verbose_name='Temperatura del suelo')),
                ('temperatura2', models.DecimalField(decimal_places=1, default=27.0, max_digits=5, max_length=6, verbose_name='Temperatura ambiental')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.area', verbose_name='Area')),
                ('Cultivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.cultivos', verbose_name='Cultivo')),
            ],
            options={
                'verbose_name': 'Temperatura',
                'verbose_name_plural': 'Temperatura',
            },
        ),
        migrations.CreateModel(
            name='Asentamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, verbose_name='Clave')),
                ('nombreAsentamiento', models.CharField(max_length=50, verbose_name='Asentamiento')),
                ('tipoZona', models.CharField(choices=[('Semi urbana', 'Semi urbana'), ('Rural', 'Rural'), ('Urbana', 'Urbana')], default='Rural', max_length=11, verbose_name='Tipo de zona')),
                ('tipoAsentamiento', models.CharField(choices=[('Ranchería', 'Ranchería'), ('Ejido', 'Ejido'), ('Pueblo', 'Pueblo')], default='Ejido', max_length=9, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Asentamiento',
                'verbose_name_plural': 'Asentamientos',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='Asentamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.asentamiento', verbose_name='Asentamiento'),
        ),
    ]
