# Generated by Django 3.2.2 on 2021-05-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asentamiento',
            name='tipoAsentamiento',
            field=models.CharField(choices=[('Ejido', 'Ejido'), ('Pueblo', 'Pueblo'), ('Ranchería', 'Ranchería')], default='Ejido', max_length=9, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='cultivos',
            name='mesDeSiembra',
            field=models.CharField(choices=[('Abril', 'Abril'), ('Septiembre', 'Septiembre'), ('Diciembre', 'Diciembre'), ('Octubre', 'Octubre'), ('Enero', 'Enero'), ('Mayo', 'Mayo'), ('Agosto', 'Agosto'), ('Febrero', 'Febrero'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Marzo', 'Marzo'), ('Noviembre', 'Noviembre')], default='Enero', max_length=30, verbose_name='Mes de siembra'),
        ),
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('Desconocido', 'Desconocido'), ('En Evaluación', 'En Evaluación'), ('En proceso', 'En proceso'), ('Iniciado', 'Iniciado'), ('Finalizado', 'Finalizado')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
