# Generated by Django 3.2.2 on 2021-05-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210506_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asentamiento',
            name='tipoAsentamiento',
            field=models.CharField(choices=[('Pueblo', 'Pueblo'), ('Ranchería', 'Ranchería'), ('Ejido', 'Ejido')], default='Ejido', max_length=9, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='asentamiento',
            name='tipoZona',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Semi urbana', 'Semi urbana'), ('Urbana', 'Urbana')], default='Rural', max_length=11, verbose_name='Tipo de zona'),
        ),
        migrations.AlterField(
            model_name='cultivos',
            name='mesDeSiembra',
            field=models.CharField(choices=[('Marzo', 'Marzo'), ('Enero', 'Enero'), ('Septiembre', 'Septiembre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Febrero', 'Febrero'), ('Julio', 'Julio'), ('Junio', 'Junio'), ('Agosto', 'Agosto'), ('Octubre', 'Octubre')], default='Enero', max_length=30, verbose_name='Mes de siembra'),
        ),
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('En Evaluación', 'En Evaluación'), ('Iniciado', 'Iniciado'), ('Finalizado', 'Finalizado'), ('Desconocido', 'Desconocido'), ('En proceso', 'En proceso')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
