# Generated by Django 3.2.2 on 2021-05-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210506_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asentamiento',
            name='tipoAsentamiento',
            field=models.CharField(choices=[('Ejido', 'Ejido'), ('Pueblo', 'Pueblo'), ('Ranchería', 'Ranchería')], default='Ejido', max_length=9, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='asentamiento',
            name='tipoZona',
            field=models.CharField(choices=[('Semi urbana', 'Semi urbana'), ('Rural', 'Rural'), ('Urbana', 'Urbana')], default='Rural', max_length=11, verbose_name='Tipo de zona'),
        ),
        migrations.AlterField(
            model_name='cultivos',
            name='mesDeSiembra',
            field=models.CharField(choices=[('Octubre', 'Octubre'), ('Marzo', 'Marzo'), ('Mayo', 'Mayo'), ('Agosto', 'Agosto'), ('Diciembre', 'Diciembre'), ('Noviembre', 'Noviembre'), ('Febrero', 'Febrero'), ('Septiembre', 'Septiembre'), ('Enero', 'Enero'), ('Junio', 'Junio'), ('Abril', 'Abril'), ('Julio', 'Julio')], default='Enero', max_length=30, verbose_name='Mes de siembra'),
        ),
        migrations.AlterField(
            model_name='plandecontingencia',
            name='activo',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Iniciado', 'Iniciado'), ('Desconocido', 'Desconocido'), ('Finalizado', 'Finalizado'), ('En Evaluación', 'En Evaluación')], default='Desconocido', max_length=13, verbose_name='Estado del plan'),
        ),
    ]
